WordsTrainer/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dictionaries
end

WordsTrainer/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

WordsTrainer/app/models/dictionary.rb
class Dictionary < ApplicationRecord
  
end

WordsTrainer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

WordsTrainer/app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  def index
    @dictionary = Dictionary.all
  end

  def new
    @dictionary = Dictionary.new
  end

  def create
    @dictionary = Dictionary.new(params[:dict_name])
    @dictionary.save
  end
end

WordsTrainer/app/helpers/application_helper.rb
module ApplicationHelper
end

WordsTrainer/app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

WordsTrainer/app/views/dictionaries/index.html.erb
<h1>Мои словари</h1>

<% @dictionary.each do |dict| %>
<h2><%= dict.dict_name%></h2>
<% end %>



<%= link_to 'Создать словарь', new_dictionary_path %>

WordsTrainer/app/views/dictionaries/new.html.erb
<h1>Создать словарь</h1>

<%= form_for @dictionary, url: { action: "create" } do |f| %>
<%= f.text_field :dict_name %>
<%= submit_tag 'Создать' %>
<% end %>

WordsTrainer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WordsTrainer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>